/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecksIndexRouteImport } from './routes/decks/index'
import { Route as ChordsIndexRouteImport } from './routes/chords/index'
import { Route as DecksDeckSlugRouteImport } from './routes/decks/$deckSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIndexRoute = DecksIndexRouteImport.update({
  id: '/decks/',
  path: '/decks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChordsIndexRoute = ChordsIndexRouteImport.update({
  id: '/chords/',
  path: '/chords/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckSlugRoute = DecksDeckSlugRouteImport.update({
  id: '/decks/$deckSlug',
  path: '/decks/$deckSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decks/$deckSlug': typeof DecksDeckSlugRoute
  '/chords/': typeof ChordsIndexRoute
  '/decks/': typeof DecksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decks/$deckSlug': typeof DecksDeckSlugRoute
  '/chords': typeof ChordsIndexRoute
  '/decks': typeof DecksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decks/$deckSlug': typeof DecksDeckSlugRoute
  '/chords/': typeof ChordsIndexRoute
  '/decks/': typeof DecksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/decks/$deckSlug' | '/chords/' | '/decks/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decks/$deckSlug' | '/chords' | '/decks'
  id: '__root__' | '/' | '/decks/$deckSlug' | '/chords/' | '/decks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecksDeckSlugRoute: typeof DecksDeckSlugRoute
  ChordsIndexRoute: typeof ChordsIndexRoute
  DecksIndexRoute: typeof DecksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/': {
      id: '/decks/'
      path: '/decks'
      fullPath: '/decks/'
      preLoaderRoute: typeof DecksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chords/': {
      id: '/chords/'
      path: '/chords'
      fullPath: '/chords/'
      preLoaderRoute: typeof ChordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckSlug': {
      id: '/decks/$deckSlug'
      path: '/decks/$deckSlug'
      fullPath: '/decks/$deckSlug'
      preLoaderRoute: typeof DecksDeckSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecksDeckSlugRoute: DecksDeckSlugRoute,
  ChordsIndexRoute: ChordsIndexRoute,
  DecksIndexRoute: DecksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
